name: Release Bundler

on: 
  workflow_dispatch:
  push:
    branches:
    - 'github-workflows'
    tags:
    - 'v*'

jobs:
  bundle-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # needs write permission to create a release.

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Configure Git
        run: |-
          git config --global --add advice.detachedHead 'false'
          echo "https://x-access-token:${PAT}@github.com" > ~/.git-credentials
          git config --global credential.helper 'store --file ~/.git-credentials'
        env:
          # needs a PAT granting read access to private repos
          PAT: ${{ secrets.REPO_READER_ACCESS_TOKEN }}

      - name: Bundle source repos into release-bundle.zip
        id: bundle
        run: >-
          ./bundle-artifacts-with-private-dependencies.sh
      - run: >-
          unzip -l release-bundle.zip

      - name: Create GitHub Release
        if: >-
          github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh release create ${{ github.ref_name }} \
            --title "Public Release ${{ github.ref_name }}" \
            --notes "A public release bundle from EOSC-Lot-1 private repositories" \
            release-bundle.zip
